---
- name: "Remove (if any) trailing slash in repository url"
  set_fact:
    crio_repository_base_url_noslash: '{{ crio_repository_base_url | regex_replace("/$", "") }}'

- name: "Set up package manager for {{ ansible_os_family }}"
  include_tasks: "config_{{ ansible_os_family }}.yml"
  when: ansible_distribution != "Fedora"

- name: "Set up Fedora specifics"
  include_tasks: config_Fedora.yml
  when: ansible_distribution == "Fedora"

- name: "Install cri-o"
  package:
    name:
      - cri-o
      - conntrack
    state: present

- name: "Install cri-o-runc"
  package:
    name: cri-o-runc
    state: present
  when: ansible_os_family == "Debian"

- name: "Install podman"
  package:
    name: podman
    state: present
  when: podman_enabled

- name: "Install podman-docker"
  package:
    name: podman-docker
    state: present
  when: podman_docker_enabled and ansible_os_family != "Debian"

- name: "Configure cri-o"
  include_tasks: configure_crio.yml

- meta: flush_handlers

- name: "Ensure cri-o service is started and enabled"
  systemd:
    name: crio
    state: started
    enabled: true
